import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Mali, } from "next/font/google";

const mali = Mali({
  weight: ["400"],
  subsets: ["latin",'thai'],
  variable: "--font-mali",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Camp for Developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
        >
          <Provider>
            <Navbar />
            <div className="container">{children}</div>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
